ndevlopi/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from course import views
from contact import views as contact_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^contact/',contact_view.contact),
    url(r'^(?P<slug>[-\w]+)/$', views.DetailCourse.as_view(),name="course"),
    url(r'^(?P<slug>[-\w]+)/(?P<chpiter_slug>[-\w]+)-(?P<pk>[0-9]{2})/$', views.detail_video,name="video"),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from urllib.request import urlopen
from re import findall
from django.shortcuts import reverse
# Create your models here.

class Course(models.Model):

    title        = models.CharField(max_length=50, help_text="your cource's title")

    short_summary= models.CharField(max_length=80, help_text="simple and short summary",blank=True,null=True)

    summary      = models.TextField(max_length=1000, help_text="Enter a brief description of the cource")

    image        = models.FileField(null=True,blank=True)

    date = models.DateField()

    github_url   = models.URLField(max_length=256,help_text="Enter the github url page that includes all commits")

    requirements = models.ManyToManyField("Requirements", help_text="Select the requirments for this book")

    authors      = models.ForeignKey("Authors",null=True,help_text="Who are the author of this cource ")

    slug         = models.SlugField(help_text="enter a slug for the course (a slug is the name in the url exemple you enter html the link will be ndevelopi/html/ ...")

    enrolled     = models.ManyToManyField(User)



    def __str__(self):
        return self.title


class Chapiter(models.Model):

    name   = models.CharField(max_length=256,help_text="your chpiter title")

    chpiterSlug = models.SlugField(null=True,blank=True,help_text="enter a slug for the course (a slug is the name in the url exemple you enter html the link will be ndevelopi/html/ ...")

    youtube_url = models.URLField(max_length=256, help_text="Enter the yourtube url playlist",blank=True,null=True)

    course = models.ForeignKey('Course',on_delete=models.CASCADE)

    completed = models.ManyToManyField(User,blank=True)

    def __str__(self):
        return self.name


class Youtube_links(models.Model):

    link = models.URLField(max_length=256,help_text="url video")

    name = models.CharField(max_length=256,null=True)

    index = models.PositiveSmallIntegerField(blank=True,null=True)

    chapiter = models.ForeignKey('Chapiter', on_delete=models.CASCADE)

    seen = models.ManyToManyField(User,blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('video', kwargs={'slug':self.chapiter.course.slug,'chpiter_slug':self.chapiter.chpiterSlug,'pk':str(self.index).zfill(2)})



def get_playlist_links(playlist_url):
    page_elements = urlopen(playlist_url).readlines()
    video_elements = [str(el,'utf-8') for el in page_elements if 'pl-video-title-link' in str(el,"utf-8")]  # Filter out unnecessary lines
    video_urls = [v.split('href="',1)[1].split('" ',1)[0] for v in video_elements]  # Grab the video urls from the elements
    return ['https://www.youtube.com/embed/' + v[9:v.index("&amp")] for v in video_urls]

def create_youtube_links(sender,**kwargs):
    if kwargs['created']:
        play_list_url = kwargs['instance'].youtube_url
        t=get_playlist_links(playlist_url=str(play_list_url))
        for count, i in enumerate(t,1):
            name = get_name(i)
            x = Youtube_links(link=i,name=name,index=count,chapiter =kwargs['instance'])
            x.save()

def get_name(link):
    html = str(urlopen(link).read(),'utf-8')
    return findall("<title>(.*?) - YouTube",html)[0]


post_save.connect(create_youtube_links,sender=Chapiter)

class Requirements(models.Model):

    name = models.CharField(max_length=150,help_text="requirment subject (like html)")

    info = models.TextField(max_length=300,help_text="basic info of what should the student learn for this subject ")

    def __str__(self):
        return self.name

class Goals(models.Model):

    name = models.CharField(max_length=150,help_text="requirment subject (like html)")

    info = models.TextField(max_length=300,help_text="basic info of what should the student learn for this subject ")

    course = models.ForeignKey('Course', on_delete=models.CASCADE)

class Authors(models.Model):

    first_name = models.CharField(max_length=100)

    last_name = models.CharField(max_length=100)

    date_of_birth = models.DateField(null=True, blank=True)

    email = models.EmailField(max_length=254)

    overview = models.TextField(max_length=1000,help_text="write a brief overview")

    instagram_acc = models.URLField(max_length=200,help_text="enter your instagram's link",blank=True,null=True)

    facebook_acc = models.URLField(max_length=200,help_text="enter your facebook's link",blank=True,null=True)

    github_acc = models.URLField(max_length=200,help_text="enter your github's link",blank=True,null=True)

    youtube_acc = models.URLField(max_length=200,help_text="enter your instagram's link",blank=True,null=True)

    def __str__(self):
        return self.last_name

course/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username","email","password1","password2")
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("This email already used")
        return data

    def save(self , commit=True):
        user = super(RegistrationForm,self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

course/views.py
from django.shortcuts import render
from django.http import Http404
from social_django.models import UserSocialAuth
# from .forms import RegistrationForm
from .models import Course,Youtube_links,Chapiter
from django.views.generic import DetailView,ListView
from django.shortcuts import get_object_or_404
# Create your views here.

# def home(request):
    # if request.user.is_authenticated():
    #     return redirect('/home/')
    # if request.method=='POST':
    #     form = RegistrationForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         return redirect('/home/')
    # else:
    #     form = RegistrationForm()
    # user = UserSocialAuth.field_names()
    # user_id = -1
    # if request.user.is_authenticated:
    #     try:
    #         user_id = request.user.social_auth.get(provider='facebook').uid
    #     except:
    #         pass
    # context = {'Course':Course.objects.all(),'user_id':user_id}
    # return render(request, 'home.html', context)
    # "user.social_auth.exists()","user.social_auth.filter(provider='facebook'):"
class Home(ListView):
    model = Course
    template_name = 'home.html'


class DetailCourse(DetailView):
    model = Course
    context_object_name = 'course'



def detail_video(request,slug,chpiter_slug,pk):
    ch= get_object_or_404(Chapiter,chpiterSlug=chpiter_slug)
    int_pk = int(pk)
    if ch.course.slug == slug:
        if int_pk == 1:
            if not (ch.course in request.user.course_set.all()):# and request.user in ch.course.enrolled.all()):
                request.user.course_set.add(ch.course)
                # ch.course.enrolled.add(request.user)
                request.user.chapiter_set.add(ch)
        videos = ch.youtube_links_set.all()
        if len(videos)<int_pk:
            raise Http404("video does not exist")
    else:
        raise Http404("course does not exist")
    context = {'chapiter':ch,'video':videos[int_pk-1]}
    return render(request,'course/detail_video.html',context)

templates/course/course_detail.html
{% extends "base.html" %}

{% block title %}{{ block.super }} || {{ course.title }}{% endblock title %}
{% block user_info %}                    <div class="parent-container">
                    {% if user.is_authenticated %}
                        <a href="" class="profile-pic">
                        <img src="http://graph.facebook.com/{{user.social_auth.all.0.uid}}/picture?width=80&height=80">
                        <h4>{{ user.get_username }} </h4>
                        </a>
                    {% endif %}{{ block.super }}
{% endblock user_info %}
{% block user_info2 %}</div>{% endblock user_info2 %}
{% block content %}


    <!--/navbar-->
    <section class="course-description">
        <div class="container">
        	<a href="{{ course.chapiter_set.all.0.youtube_links_set.all.0.get_absolute_url }}" class="enroll-container">
        		<div class="enroll">
        			<div><i class="fa fa-play" aria-hidden="true"></i></div>
        		</div>
        		<p>تعلم الآن</p>
        	</a>
            <div class="description-container">
            	<h3>{{ course.title }} : {{ course.short_summary }}</h3>
            	<p class="description">{{ course.summary }}</p>
            	<h4>إعداد : {{ course.authors.first_name }} {{ course.authors.last_name }}</h4>
            	<p class="date">بتاريخ : {{ course.date }}</p>
            </div>
        </div>
    </section>

    <section class="what-to-learn">
        <div class="container">
            <h2>ما ستتعلمه في هذه الدورة.</h2>
            <ol>
                {% for goal in course.goals_set.all %}
                    <li><i class="fa fa-check" aria-hidden="true"></i>{{ goal.name }}</li>
                {% endfor %}
            </ol>
        </div>
        <!--/container-->
    </section>
    <!--/what-to-learn-->

       <section class="requirements">
        <!--requirements-->
        <div class="container">
            <h2>المهارات المتطلبة</h2>
            <ol>
                {% for requirment in course.requirements.all %}
                    <li><i class="fa fa-exclamation-triangle" aria-hidden="true"></i>{{ requirment.name }}</li>
                {% endfor %}
            </ol>
        </div>
    </section>
    <!--/requirements-->
    <section class="program">
        <div class="container">
            <div>
                <div>
                    <h3>دروس الدورة</h3>
                    <ol>
                        {% for chapiter in course.chapiter_set.all  %}
                            <a href=""><li>{{ chapiter.name }}</li></a>
                        {% endfor %}
                    </ol>

                </div>
            </div>
        </div>
        <!--/container-->
    </section>
    <!--/program-->
    <section class="teacher">
        <!--teacher-->
        <div class="container">
            <div>
                <img src="https://scontent.ftun3-1.fna.fbcdn.net/v/t1.0-9/14991971_1287845641266502_6249374057998587611_n.jpg?oh=5c5b2111948cba0bb5bd953fcdaf97c6&oe=5A838DB8">
                <div class="teacher-description">
                	<h2>{{ course.authors.first_name }} {{ course.authors.last_name }}</h2>
               		 <p>{{ course.authors.overview }}</p>
                </div>
            </div>
            <ol class="social">
                <a href="">
                    <li class="fb"><i class="fa fa-facebook" aria-hidden="true"></i></li>
                </a>
                <a href="">
                    <li class="ytb"><i class="fa fa-youtube" aria-hidden="true"></i></li>
                </a>
                <a href="">
                    <li class="instagram"><i class="fa fa-instagram" aria-hidden="true"></i></li>
                </a>
                <a href="">
                    <li class="github"><i class="fa fa-github" aria-hidden="true"></i></li>
                </a>
            </ol>
        </div>
    </section>
    <!--/teacher-->
{% endblock content %}

templates/course/detail_video.html
{% extends "base.html" %}

{% block content %}
<section class="videos">
        <div class="videos-container">

        <div class="videos-list" >
            <h2 class="course-title">{{ chapiter.name }}</h2>
            <ol>
                {% for v in chapiter.youtube_links_set.all %}
                    <a href="{{ v.get_absolute_url }}"><li>{{ v.name }}</li></a>
                {% endfor %}
            </ol>
        </div>
        <div class="video">

        <div class="container">
            <h2 class="video-title">{{ video.name }}</h2>
            <iframe  src="{{ video.link }}" frameborder="0" gesture="media" allowfullscreen></iframe>
            <p>انه ببعض مسؤولية في. إذ كما خيار العالمية, هو ضرب أراضي ومحاولة, هو مكن اعتداء أسابيع استراليا،. جهة دارت معقل مسرح بل</p>
            <button>التالي</button>
         </div>
        </div>
    </div><!--/container-->
    </section>

    <!--/videos-->

{% endblock content %}

templates/course/youtube_links_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ video.name }}</title>
</head>
<body>

</body>
</html>