ndevlopi/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from course import views
from contact import views as contact_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^contact/',contact_view.contact),
    url(r'^(?P<slug>[-\w]+)/$', views.DetailCourse.as_view(),name="course"),
    url(r'^(?P<slug>[-\w]+)/(?P<chpiter_slug>[-\w]+)-(?P<pk>[0-9]{2})/$', views.detail_video,name="video"),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from urllib.request import urlopen
from re import findall
from django.shortcuts import reverse
# Create your models here.

class Course(models.Model):

    title        = models.CharField(max_length=50, help_text="your cource's title")

    short_summary= models.CharField(max_length=80, help_text="simple and short summary",blank=True,null=True)

    summary      = models.TextField(max_length=1000, help_text="Enter a brief description of the cource")

    image        = models.FileField(null=True,blank=True)

    date = models.DateField()

    github_url   = models.URLField(max_length=256,help_text="Enter the github url page that includes all commits")

    requirements = models.ManyToManyField("Requirements", help_text="Select the requirments for this book")

    authors      = models.ForeignKey("Authors",null=True,help_text="Who are the author of this cource ")

    slug         = models.SlugField(help_text="enter a slug for the course (a slug is the name in the url exemple you enter html the link will be ndevelopi/html/ ...")

    enrolled     = models.ManyToManyField(User)



    def __str__(self):
        return self.title


class Chapiter(models.Model):

    name   = models.CharField(max_length=256,help_text="your chpiter title")

    chpiterSlug = models.SlugField(null=True,blank=True,help_text="enter a slug for the course (a slug is the name in the url exemple you enter html the link will be ndevelopi/html/ ...")

    youtube_url = models.URLField(max_length=256, help_text="Enter the yourtube url playlist",blank=True,null=True)

    course = models.ForeignKey('Course',on_delete=models.CASCADE)

    completed = models.ManyToManyField(User,blank=True)

    def __str__(self):
        return self.name


class Youtube_links(models.Model):

    link = models.URLField(max_length=256,help_text="url video")

    name = models.CharField(max_length=256,null=True)

    index = models.PositiveSmallIntegerField(blank=True,null=True)

    chapiter = models.ForeignKey('Chapiter', on_delete=models.CASCADE)

    seen = models.ManyToManyField(User,blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('video', kwargs={'slug':self.chapiter.course.slug,'chpiter_slug':self.chapiter.chpiterSlug,'pk':str(self.index).zfill(2)})



def get_playlist_links(playlist_url):
    page_elements = urlopen(playlist_url).readlines()
    video_elements = [str(el,'utf-8') for el in page_elements if 'pl-video-title-link' in str(el,"utf-8")]  # Filter out unnecessary lines
    video_urls = [v.split('href="',1)[1].split('" ',1)[0] for v in video_elements]  # Grab the video urls from the elements
    return ['https://www.youtube.com/embed/' + v[9:v.index("&amp")] for v in video_urls]

def create_youtube_links(sender,**kwargs):
    if kwargs['created']:
        play_list_url = kwargs['instance'].youtube_url
        t=get_playlist_links(playlist_url=str(play_list_url))
        for count, i in enumerate(t,1):
            name = get_name(i)
            x = Youtube_links(link=i,name=name,index=count,chapiter =kwargs['instance'])
            x.save()

def get_name(link):
    html = str(urlopen(link).read(),'utf-8')
    return findall("<title>(.*?) - YouTube",html)[0]


post_save.connect(create_youtube_links,sender=Chapiter)

class Requirements(models.Model):

    name = models.CharField(max_length=150,help_text="requirment subject (like html)")

    info = models.TextField(max_length=300,help_text="basic info of what should the student learn for this subject ")

    def __str__(self):
        return self.name

class Goals(models.Model):

    name = models.CharField(max_length=150,help_text="requirment subject (like html)")

    info = models.TextField(max_length=300,help_text="basic info of what should the student learn for this subject ")

    course = models.ForeignKey('Course', on_delete=models.CASCADE)

class Authors(models.Model):

    first_name = models.CharField(max_length=100)

    last_name = models.CharField(max_length=100)

    date_of_birth = models.DateField(null=True, blank=True)

    email = models.EmailField(max_length=254)

    overview = models.TextField(max_length=1000,help_text="write a brief overview")

    instagram_acc = models.URLField(max_length=200,help_text="enter your instagram's link",blank=True,null=True)

    facebook_acc = models.URLField(max_length=200,help_text="enter your facebook's link",blank=True,null=True)

    github_acc = models.URLField(max_length=200,help_text="enter your github's link",blank=True,null=True)

    youtube_acc = models.URLField(max_length=200,help_text="enter your instagram's link",blank=True,null=True)

    def __str__(self):
        return self.last_name

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}نديفلوبي{% endblock title %}</title>
	<meta name="viewport" content="width=device-width initial-scale=1.0">
	<meta charset="utf-8">
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%} ">
    <link href="https://fonts.googleapis.com/css?family=Changa" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/prism.css'%} ">
</head>
<body>
	<!--header-->
		{% block header %}{% endblock %}

				<nav>
                {% block user_info %}{% endblock user_info %}
                    <ol>
                        <a href="{% url 'home' %}" class="logo"><li>نديفلوبي</li></a>
                        <a href="{% url 'home' %}"><li>الرئيسية</li></a>
                        <a href=""><li>دروس </li></a>
                        <a href=""><li>مقالات</li></a>
                        <a href=""><li>مسارات التعليم</li></a>
                    </ol>
                    {% block user_info2 %}{% endblock user_info2 %}
                </nav>
            {% block content %}
            {% block header2 %}{% endblock header2 %}
            {% endblock content %}
        <footer>
			<div class="container">
				<p> نقطة ميناء ما قام. بـ نفس جدول وبحلول مقاومة, ما وبعض وتنصيب سنغافورة أما. من تعد الآلاف حاملات التنازلي, أجزاء والحزب أم بحث.</p>
				<ol class="social">
					<a href=""><li class="fb"><i class="fa fa-facebook" aria-hidden="true"></i></li></a>
					<a href=""><li class="ytb" ><i class="fa fa-youtube" aria-hidden="true"></i></li></a>
					<a href=""><li class="instagram"><i class="fa fa-instagram" aria-hidden="true"></i></li></a>
					<a href=""><li class="github"><i class="fa fa-github" aria-hidden="true"></i></li></a>
				</ol>
				<h5>كل الحقوق محفوظة © 2017</h5>
			</div>
		</footer>



	<!--scripts-->
    <script type="text/javascript" src="{% static 'js/prism.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/index.js'%}"></script>
    <script type="text/javascript">
            var el = document.querySelector('.videos-list');
            SimpleScrollbar.initEl(el);
    </script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}{{ block.super }} || الرئيسة{% endblock title %}
{% block header %}<header>{% endblock %}
{% block user_info %}                    <div class="parent-container">
                    {% if user.is_authenticated %}
                        <a href="" class="profile-pic">
                        <img src="http://graph.facebook.com/{{user.social_auth.all.0.uid}}/picture?width=80&height=80">
                        <h4>{{ user.get_username }} </h4>
                        </a>
                    {% endif %}{{ block.super }}
{% endblock user_info %}
{% block user_info2 %}</div>{% endblock user_info2 %}
{% block content %}

<div class="container"><!--container -->
					<div class="slogan_container">
                        {% load static %}
						<img src="{% static 'images/bg.gif' %}">
						<div class="slogan">
							<h2>تعلم تطوير صفحات الويب<br> و  البرمجة</h2>
							<p>نوفر لكم دروس مجانية في تصميم و تطوير صفحات الويب كما نوفر دروس لتبدئ في  تعلم البرمجة. سنساعدكم في تطوير مهارتكم و في حل الصعوبات التي تواجهكم.</p>
                            {% if not user.is_authenticated %}
                                <a href="{% url 'social:begin' 'facebook' %}"><button><i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i>دخول بحساب فايسبوك</button></a>
						    {% endif %}
                        </div><!--/slogan-->
					</div><!--/ -->
				</div>

		{% block header2 %}</header><!--/header-->{% endblock header2 %}

		<section class="courses">
			<div class="switch-titles">
				<a href=""><h3>كل الدروس</h3></a>
				{% if user.is_authenticated %}
                    <a href=""><h3>دروسي</h3></a>
                {% endif %}
			</div>
			<div class="container">
                {% if user.is_authenticated %}
                    {% for c in user.course_set.all %}
                        <a href="{{c.slug}}" class="card my-course">
                            <img src="{{ c.image.url }}">
                            <div class="overlay"></div>
                            <h3>{{ c.title }}</h3>
                            <p>{{ c.summary }}</p>
                        </a>
                    {% endfor %}
                {% endif %}
				{% for c in course_list %}
                <a href="{{c.slug}}" class="card all">
					<img src="{{ c.image.url }}">
					<div class="overlay"></div>
					<h3>{{ c.title }}</h3>
					<p>{{ c.summary }}</p>
				</a>
                {% endfor %}
			</div><!--/container-->

		</section><!--/courses-->

		<section class="discover">
			<div class="main">
				<div>
					<h2> <i class="fa fa-paper-plane" aria-hidden="true"></i>مغامرة جديدة </h2>
					<p>استعد للغوص في عالم الويب و البرمجة بواسطة دروسنا المبسّطة و التي التي تستهدف جميع الأعمار.</p>
					<a href=""><button>إبدأ الآن</button></a>
				</div>
			</div>
		</section><!--/discover-->

		<section class="path">
			<h1>خطوات التعلم معنا</h1>
			<div class="container">
				<div class="step">
					<i class="fa fa-book" aria-hidden="true"></i>
					<div class="description">
						<h2>سجّل في دروس تطوير الويب و البرمجة</h2>
						<p>لأرض وأكثرها يتم هو. ذلك الشمال المشترك استطاعوا أن. ثم والقرى الرئيسية بها. جعل ٣٠ اللا وإعلان الأسيوي, نقطة ميناء ما قام. بـ نفس جدول وبحلول مقاومة, ما وبعض وتنصيب سنغافورة أما. من تعد الآلاف حاملات التنازلي, أجزاء والحزب أم بحث. لكل قد أكثر أملاً.</p>
					</div>
				</div>
				<div class="step">
					<div class="description">
						<h2>طبق ما تعلمته بتطوير موقع الويب الخاص بك</h2>
						<p>لأرض وأكثرها يتم هو. ذلك الشمال المشترك استطاعوا أن. ثم والقرى الرئيسية بها. جعل ٣٠ اللا وإعلان الأسيوي, نقطة ميناء ما قام. بـ نفس جدول وبحلول مقاومة, ما وبعض وتنصيب سنغافورة أما. من تعد الآلاف حاملات التنازلي, أجزاء والحزب أم بحث. لكل قد أكثر أملاً.</p>
					</div>
					<i class="fa fa-code" aria-hidden="true"></i>

				</div>
				<div class="step">
					<i class="fa fa-briefcase" aria-hidden="true"></i>
					<div class="description">
						<h2>إبدأ مسيرك المهنية كمبرمج أو مطور ويب.</h2>
						<p>لأرض وأكثرها يتم هو. ذلك الشمال المشترك استطاعوا أن. ثم والقرى الرئيسية بها. جعل ٣٠ اللا وإعلان الأسيوي, نقطة ميناء ما قام. بـ نفس جدول وبحلول مقاومة, ما وبعض وتنصيب سنغافورة أما. من تعد الآلاف حاملات التنازلي, أجزاء والحزب أم بحث. لكل قد أكثر أملاً.</p>
					</div>
				</div>
			</div><!--/container-->
		</section>

		<section class="contact">
			<div class="mother">
				<div class="container">
				<h2>إتصل بنا</h2>
				<p>وبالرغم, معقل وانهاء ومحاولة تم الا. بـ شاسعة اكتوبر المعاهدات حول. كل كان سكان مسؤولية, اوروبا الساحلية أي تعد. هذا تطوير الإتحاد عل, دأبوا وبدون لإعلان وتم</p>
				<a href=""><button>راسلنا الآن</button></a>
			</div>
			</div>
		</section>
{% endblock content %}